"""add timestamps to users

Revision ID: 105a7204c738
Revises: f38f44f2df66
Create Date: 2026-03-28 03:14:45.007578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105a7204c738'
down_revision: Union[str, Sequence[str], None] = 'f38f44f2df66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
