"""add project_type to project_files

Revision ID: 739b42ae8374
Revises: 089421974990
Create Date: 2026-06-16 07:27:36.845660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739b42ae8374'
down_revision: Union[str, Sequence[str], None] = '089421974990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_files', sa.Column('project_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_project_files_project_type'), 'project_files', ['project_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_files_project_type'), table_name='project_files')
    op.drop_column('project_files', 'project_type')
    # ### end Alembic commands ###
