"""add timestamps to users

Revision ID: 8df290883a5d
Revises: 90857b56417d
Create Date: 2026-03-28 12:11:19.264008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8df290883a5d'
down_revision: Union[str, Sequence[str], None] = '90857b56417d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('subscribed', 'unsubscribed', 'bounced', 'pending', name='newsletterstatus'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletters_email'), 'newsletters', ['email'], unique=True)
    op.create_index(op.f('ix_newsletters_id'), 'newsletters', ['id'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_message', sa.Text(), nullable=True),
    sa.Column('custom_message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('meta', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_audits_action'), 'audits', ['action'], unique=False)
    op.create_index(op.f('ix_audits_actor_user_id'), 'audits', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audits_created_at'), 'audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_audits_id'), 'audits', ['id'], unique=False)
    op.create_index(op.f('ix_audits_is_read'), 'audits', ['is_read'], unique=False)
    op.create_index('ix_audits_is_read_created_at', 'audits', ['is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_audits_target_user_id'), 'audits', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audits_target_user_id'), table_name='audits')
    op.drop_index('ix_audits_is_read_created_at', table_name='audits')
    op.drop_index(op.f('ix_audits_is_read'), table_name='audits')
    op.drop_index(op.f('ix_audits_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_created_at'), table_name='audits')
    op.drop_index(op.f('ix_audits_actor_user_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_action'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_newsletters_id'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_email'), table_name='newsletters')
    op.drop_table('newsletters')
    # ### end Alembic commands ###
